const express=require('express')
const admin_route=express()
const path=require('path')
const jwt=require('jsonwebtoken')
const adminJwt=require('../middleware/adminauthMiddleware')
const {upload}=require('../multer/multer')
const Admincontroller=require('../controller/admin-controller')
admin_route.get('/',Admincontroller.loginpage)
admin_route.post('/login',Admincontroller.adminlogin)
admin_route.get('/home',adminJwt.protected,Admincontroller.homepage)
admin_route.put('/updateUser/:id',upload.single('image'),Admincontroller.updateUser)
admin_route.delete('/deleteUser/:id',Admincontroller.deleteUser)
admin_route.post('/createUser',Admincontroller.createUser)
admin_route.get('/searchUser',Admincontroller.searchUser)
//admin_route.get('/logout',)
//admin_route.get('/admin',Admincontroller)
//admin_route.get('/',Admincontroller)

module.exports=admin_route